### ISSUE TITLE
User should be able to export chart data

### ISSUE THREAD

**Issue by denniskuczynski** [leafygreen/mops-cli#5]
User should be able to export chart data for a host.
- CSV format?
- Chart data should be able to generate charts (external utility? R? gnuplot?)

**Comment by PeaSeaGee** [comment]
Do we want to give them an option to export all of their metrics data?
Should we build in a throttler so we don't slam Cloud Manager?

**Comment by denniskuczynski** [comment]
i was thinking of exporting all for a host.  It's probably Cloud Manager's job to throttle us. :smile_cat:

**Comment by denniskuczynski** [comment]
We can experiment with the details once there's a prototype version.
